# Codecov configuration
# https://docs.codecov.io/docs/codecovyml-reference

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 70%
        threshold: 5%

# All code should be tested - no files are excluded from coverage
